"use client"

import { ToastContainer } from "react-toastify";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

const inter = Open_Sans({ subsets: ["latin"] });

const metadata = {
  title: "CuriouzKids.com",
  description: "Generated by the Creos Work Force",
  image: "logo.svg",
};
// process.env.NODE_NO_WARNINGS = 'stream/web';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>{children}</Provider>
        <ToastContainer />
      </body>
    </html>
  );
}
