"use client"

import { ToastContainer } from "react-toastify";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

const inter = Open_Sans({ subsets: ["latin"] });

// export const metadata = {
//   title: "Creoslab.com",
//   description: "Generated by the Creos Work Force",
//   image: "logo.svg",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>{children}</Provider>
        <ToastContainer />
      </body>
    </html>
  );
}
